#!/bin/bash

## Get data
STATUS="$(playerctl status)"
SHUFFLE="$(playerctl shuffle)"
LOOP="$(playerctl loop)"

## Get play status
get_play_status() {
	if [ "$STATUS" == "Playing" ]; then
		echo ""
	else
		echo "喇"
	fi
}

## Get shuffle status
get_shuffle_status() {
	if [ "$SHUFFLE" == "On" ]; then
		echo ""
	else
		echo "#696969"
	fi
}

## Get loop status
get_loop_status() {
	if [ "$LOOP" == "Playlist" ]; then
		echo ""
	else
		echo "#696969"
	fi
}

## Get song
get_song() {
  song="$(playerctl metadata xesam:title)"
	if [[ -z "$song" ]]; then
		echo "Offline"
	else
		echo "$song"
	fi
}

## Get artist
get_artist() {
	artist="$(playerctl metadata xesam:artist)"
	if [[ -z "$artist" ]]; then
		echo ""
	else
		echo "$artist"
	fi
}


## Get cover
get_cover() {
  if [ "$STATUS" = "Playing" ] || [ "$STATUS" == "Paused" ];then
    echo "$(playerctl metadata mpris:artUrl)"
  else
    echo "img/music"
  fi
}

## Toggle play status
play() {
  playerctl play-pause
}

## Next
next() {
  playerctl next
}

## Previous
previous() {
  playerctl previous
}

## Toggle shuffle status
shuffle() {
	playerctl shuffle Toggle
}

## Toggle loop status
loop() {
	if [ "$LOOP" == "Playlist" ]; then
    playerctl loop None
  else
  	playerctl loop Playlist
  fi
}

## Execute accordingly
if [[ "$1" == "--song" ]]; then
	get_song
elif [[ "$1" == "--artist" ]]; then
	get_artist
elif [[ "$1" == "--play_status" ]]; then
	get_play_status
elif [[ "$1" == "--shuffle_status" ]]; then
	get_shuffle_status
elif [[ "$1" == "--loop_status" ]]; then
	get_loop_status
elif [[ "$1" == "--cover" ]]; then
	get_cover
elif [[ "$1" == "--play" ]]; then
	play
elif [[ "$1" == "--next" ]]; then
	next
elif [[ "$1" == "--prev" ]]; then
	previous
elif [[ "$1" == "--shuffle" ]]; then
	shuffle
elif [[ "$1" == "--loop" ]]; then
	loop
fi

