#!/bin/bash
FILE="$HOME/.cache/eww_launch"

if [[ "$1" == "--lock" ]]; then
	swaylock
elif [[ "$1" == "--logout" ]]; then
	loginctl kill-session self
elif [[ "$1" == "--suspend" ]]; then
	loginctl suspend
elif [[ "$1" == "--reboot" ]]; then
	loginctl reboot
elif [[ "$1" == "--poweroff" ]]; then
	loginctl poweroff
eww close music powerbuttons
 	rm "$FILE"
fi

